### ISSUE TITLE
请问，我使用./autogen.sh 后生成链接还是打不开是怎么回事呢？

### ISSUE THREAD

**Issue by return1234567890** [yuanxinyu/kaola#1]
使用./autogen.sh 后生成的信息如下：
.
retry {:DEFAULT=>[]}
警告： 表名userss的复数规则有问题

**Comment by yuanxinyu** [comment]
你的问题解决了吗？ 
./autogen.sh 只是生成代码罢了，警告不影响代码的生成。
要能够通过网络访问，还需要启动web server。方式有很多种，最简单的就是运行rails s

**Comment by yuanxinyu** [comment]
更新了代码，以解决rails s不支持ipv6导致启动失败的问题
